AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
    InvertirOnlinePassword:
        Type: String
        Default: password
    InvertirOnlineUsername:
        Type: String
        Default: username
Description: >
    AWS Serverless Application for trading

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
    Function:
        Timeout: 140

Resources:
    TradingCommonFunctions:
        Type: AWS::Serverless::LayerVersion
        Properties:
            LayerName: TradingCommonFunctions
            Description: Funciones comunes de Trading
            ContentUri: ./commons/python.zip
            CompatibleRuntimes:
              - python3.7
              - python3.6
    GetShareHistory:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: ./history
            Handler: get_share_history.get_historical_share_handler
            Runtime: python3.6
            Role: 'arn:aws:iam::382744615649:role/service-role/invertir_lambda_role' #Tiene permisos para acceder a S3
            Environment:
                Variables:
                    INVERTIRONLINE_PASSWORD: !Ref InvertirOnlinePassword
                    INVERTIRONLINE_USERNAME: !Ref InvertirOnlineUsername
            Events:
                getSharesHistory:
                    Type: Api
                    Properties:
                        Path: /history/{index}/{share}
                        Method: POST
            Layers:
                - !Ref TradingCommonFunctions
    GetIndexes:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: ./indexes
            Handler: get_indexes.get_indexes
            Runtime: python3.6
            Role: 'arn:aws:iam::382744615649:role/service-role/invertir_lambda_role' #Tiene permisos para acceder a S3
            Events:
                getSharesHistory:
                    Type: Api
                    Properties:
                        Path: /indexes
                        Method: GET
            Layers:
                - !Ref TradingCommonFunctions

Outputs:
    GetShareHistory:
      Description: "GetShareHistory Lambda Function ARN"
      Value: !GetAtt GetShareHistory.Arn
    GetIndexes:
        Description: "GetIndexes Lambda Function ARN"
        Value: !GetAtt GetIndexes.Arn